export const Characters = [
    'Black Panther',
    'Captain America',
    'Captain Marvel',
    'Doctor Strange',
    'Dormammu',
    'Gamora',
    'Ghost Rider',
    'Hawkeye',
    'Hulk',
    'Iron Man',
    'Nova',
    'Rocket Raccoon',
    'Spider-Man',
    'Thanos',
    'Thor',
    'Ultron',
    'Arthur',
    'Chris Redfield',
    'Chun-Li',
    'Dante',
    'Firebrand',
    'Frank West',
    'Jedah Dohma',
    'Mega Man X',
    'Haggar',
    'Morrigan Aensland',
    'Nemesis',
    'Nathan Spencer',
    'Ryu',
    'Sigma',
    'Strider Hiryu',
    'Zero'
]


